Update Devirtualize - Make the graph static

diff --git a/click-buildtool.in b/click-buildtool.in
--- a/click-buildtool.in
+++ b/click-buildtool.in
@@ -425,7 +425,7 @@ $bad_first_files" | sort | uniq -u`
 	    files="$files
 ${ppfx}$i"
 	fi
-	if expr "$checksum_data" != "" '&' "${ppfx}$i" : '[^$ 	
+	if expr "$checksum_data" != "" '&' "${ppfx}$i" : '[^$
 ]*$' >/dev/null; then
 	    checksum_files="$checksum_files ${ppfx}$i"
 	elif test -n "$checksum_data"; then rm -f "$checksum_data"; checksum_data=; fi
@@ -920,6 +920,7 @@ END {
 
 elem2xxx () {
     package=""
+    packagellvm=""
     date=`date`
     standards=''
     includes=''
@@ -958,6 +959,25 @@ is the name of the package.
 
 Usage: click-buildtool elem2package [-p PREFIX] [-V] PKGNAME < elements.conf
 EOF
+    elif test "$elem2" = exportllvm; then
+	    cat <<'EOF' 1>&2
+'Click-buildtool elem2exportllvm' reads an 'elements.conf' file generated by
+'click-buildtool findelem' on the standard input, examines those files for
+exported elements, and writes a C++ source file defining the
+click_export_elements() function to the standard output.
+
+Usage: click-buildtool elem2exportllvm [-V] < elements.conf
+EOF
+	elif test "$elem2" = packagellvm; then
+	    cat <<'EOF' 1>&2
+'Click-buildtool elem2packagellvm' reads an 'elements.conf' file generated by
+'click-buildtool findelem' on the standard input, examines those files for
+exported elements, and writes a C++ source file suitable for creating a
+dynamically linked package with those elements to the standard output. PKGNAME
+is the name of the package.
+
+Usage: click-buildtool elem2packagellvm [-p PREFIX] [-V] PKGNAME < elements.conf
+EOF
 	fi
 	cat <<'EOF' 1>&2
 
@@ -973,7 +993,7 @@ EOF
     -*)
 	elem2xxx_usage;;
     *)
-	if test -z "$package" -a "$elem2" = package; then package="$1"; shift 1; else elem2xxx_usage; fi;;
+	if test -z "$package" -a "$elem2" = package; then package="$1"; shift 1; elif test -z "$packagellvm" -a "$elem2" = packagellvm; then packagellvm="$1"; shift 1; else elem2xxx_usage; fi;;
     esac
     done
 
@@ -1023,7 +1043,95 @@ END {
   print "#ifdef CLICK_BSDMODULE\n  return 0;\n  } else\n    return 0;\n}\nstatic moduledata_t modinfo = {\n  \"", packname, "\", modevent, 0\n};\nDECLARE_MODULE(", packname, ", modinfo, SI_SUB_PSEUDO, SI_ORDER_ANY);\nMODULE_VERSION(", packname, ", 1);\nMODULE_DEPEND(", packname, ", click, 1, 1, 1);\n#else\n}\n#endif";
 }
 '
-
+    elif test -n "$packagellvm"; then
+	includes="  $includes "'print "#define WANT_MOD_USE_COUNT 1\n#include <click/config.h>\n#include <click/package.hh>\n#include <click/glue.hh>", includefiles;'
+	awk_program='BEGIN {
+  OFS = ""; nrebecca = 0; packname="'"$packagellvm"'"; includefiles=""
+}
+/^#/ { next; }
+{
+  if (NF == 1)
+    next;
+  anyprovides = 0;
+  for (i = 3; i <= NF; i++) {
+    split($i, ans, /-/);
+    if (ans[2] == "!si") {
+      B = B "  " ans[1] "::static_initialize();\n";
+      anyprovides++;
+    } else if (ans[2] == "!sc") {
+      C = C "  " ans[1] "::static_cleanup();\n";
+      anyprovides++;
+    } else if (ans[2] !~ /^!/) {
+      B = B "  hatred_of_rebecca[" nrebecca "] = click_add_element_type(\"" ans[2] "\", beetlemonkey, " nrebecca ");\n"
+      C = C "  click_remove_element_type(hatred_of_rebecca[" nrebecca "]);\n";
+      D = D "   case " nrebecca ": return &obj_" ans[1] ";\n";
+      E = E "extern " ans[1] " obj_"ans[1]";\n";
+      anyprovides++; nrebecca++;
+    }
+  }
+  if (anyprovides && !($2 in INCLUDES) && $2 != "-") {
+    includefiles = includefiles "\n#include " $2;
+    INCLUDES[$2] = 1;
+  }
+}
+END {
+  print "/* Generated by \"click-buildtool elem2packagellvm\" on '"$date"' */";
+  print "/* Package name: ", packname, " */\n";
+'"$includes"'
+  print E;
+  print "extern AverageCounter obj_AverageCounter;\n";
+  print "\nCLICK_USING_DECLS";
+  print "static int hatred_of_rebecca[", nrebecca, "];";
+  print "static Element *\nbeetlemonkey(uintptr_t heywood)\n{\n  switch (heywood) {\n", D, "   default: return 0;\n  }\n}\n";
+  print "#ifdef CLICK_LINUXMODULE\n#define click_add_element_type(n, f, t) click_add_element_type((n), (f), (t), THIS_MODULE)\n#endif";
+  print "#ifdef CLICK_BSDMODULE\nstatic int\nmodevent(module_t, int t, void *)\n{\n  if (t == MOD_LOAD) {\n#else\nextern \"C\" int\ninit_module()\n{\n#endif";
+  print "  click_provide(\"", packname, "\");\n", B, "  CLICK_DMALLOC_REG(\"nXXX\");\n  return 0;";
+  print "#ifdef CLICK_BSDMODULE\n  } else if (t == MOD_UNLOAD) {\n#else\n}\nextern \"C\" void\ncleanup_module()\n{\n#endif";
+  print C, "  click_unprovide(\"", packname, "\");";
+  print "#ifdef CLICK_BSDMODULE\n  return 0;\n  } else\n    return 0;\n}\nstatic moduledata_t modinfo = {\n  \"", packname, "\", modevent, 0\n};\nDECLARE_MODULE(", packname, ", modinfo, SI_SUB_PSEUDO, SI_ORDER_ANY);\nMODULE_VERSION(", packname, ", 1);\nMODULE_DEPEND(", packname, ", click, 1, 1, 1);\n#else\n}\n#endif";
+}
+'
+elif test "$elem2" = exportllvm; then
+	includes="$includes"'  print "#include <click/config.h>\n#include <click/package.hh>", includefiles;'
+	awk_program='BEGIN {
+  OFS = ""; nrebecca = 0;
+}
+/^#/ { next; }
+{
+  if (NF == 1)
+    next;
+  anyprovides = 0;
+  for (i = 3; i <= NF; i++) {
+    split($i, ans, /-/);
+    if (ans[2] == "!si") {
+      B = B "  " ans[1] "::static_initialize();\n";
+      anyprovides++;
+    } else if (ans[2] == "!sc") {
+      C = C "  " ans[1] "::static_cleanup();\n";
+      anyprovides++;
+    } else if (ans[2] !~ /^!/) {
+      B = B "  (void) click_add_element_type_stable(\"" ans[2] "\", beetlemonkey, " nrebecca ");\n";
+      D = D "   case " nrebecca ": return &obj_" ans[1] ";\n";
+      E = E " " ans[1] " obj_"ans[1]";\n";
+      anyprovides++; nrebecca++;
+    }
+  }
+  if (anyprovides && !($2 in INCLUDES) && $2 != "-") {
+    includefiles = includefiles "\n#include " $2;
+    INCLUDES[$2] = 1;
+  }
+}
+END {
+  print "/* Generated by \"click-buildtool elem2exportllvm\" on '"$date"' */\n";
+'"$includes"'
+  print E;
+  print "CLICK_USING_DECLS";
+  print "static Element *\nbeetlemonkey(uintptr_t heywood)\n{\n  switch (heywood) {\n", D, "   default: return 0;\n  }\n}\n";
+  print "#ifdef CLICK_LINUXMODULE\n#define click_add_element_type_stable(n, f, t) click_add_element_type_stable((n), (f), (t), 0)\n#endif";
+  print "void\nclick_export_elements()\n{\n", B, "  CLICK_DMALLOC_REG(\"nXXX\");\n}\n";
+  print "void\nclick_unexport_elements()\n{\n", C, "}";
+}
+'
     else
 	includes="$includes"'  print "#include <click/config.h>\n#include <click/package.hh>", includefiles;'
 	awk_program='BEGIN {
@@ -1629,6 +1737,8 @@ on a particular tool, run 'click-buildtool TOOLNAME --help'.
 Usage: click-buildtool elem2make [-V] [-p PREFIX] < [ELEMENTS]
    or: click-buildtool elem2export [-V] [-p PREFIX] < [ELEMENTS]
    or: click-buildtool elem2package [-V] [-p PREFIX] PACKAGENAME < [ELEMENTS]
+   or: click-buildtool elem2exportllvm [-V] [-p PREFIX] < [ELEMENTS]
+   or: click-buildtool elem2packagellvm [-V] [-p PREFIX] PACKAGENAME < [ELEMENTS]
    or: click-buildtool findelem [-a] [-V] [-p PREFIX] < [FILES AND DIRECTORIES]
    or: click-buildtool makepackage [-t DRIVER] PACKAGENAME SRCFILES...
    or: click-buildtool prefix
@@ -1658,6 +1768,10 @@ EOF
      elem2="export"; shift 1; elem2xxx "$@"; exit 0;;
   elem2package)
      elem2="package"; shift 1; elem2xxx "$@"; exit 0;;
+  elem2exportllvm)
+       elem2="exportllvm"; shift 1; elem2xxx "$@"; exit 0;;
+  elem2packagellvm)
+     elem2="packagellvm"; shift 1; elem2xxx "$@"; exit 0;;
   makepackage)
      shift 1; makepackage "$@"; exit 0;;
   prefix)
