Merge most of PacketMill
Just not the RAND_ALIGN which was only a paper feature, and not
DPDK_INSIDE that was to simulate VPP model, not entierly finished and is
not the right choice anyway.

diff --git a/click-buildtool.in b/click-buildtool.in
--- a/click-buildtool.in
+++ b/click-buildtool.in
@@ -928,6 +928,7 @@ END {
 
 elem2xxx () {
     package=""
+    packagestatic=""
     date=`date`
     standards=''
     includes=''
@@ -966,6 +967,33 @@ is the name of the package.
 
 Usage: click-buildtool elem2package [-p PREFIX] [-V] PKGNAME < elements.conf
 EOF
+elif test "$elem2" = list; then
+	    cat <<'EOF' 1>&2
+'Click-buildtool elem2list' reads an 'elements.conf' file generated by
+'click-buildtool findelem' on the standard input, examines those files for
+exported elements, and writes a list of element names.
+
+Usage: click-buildtool elem2list < elements.conf
+EOF
+    elif test "$elem2" = exportstatic; then
+	    cat <<'EOF' 1>&2
+'Click-buildtool elem2exportstatic' reads an 'elements.conf' file generated by
+'click-buildtool findelem' on the standard input, examines those files for
+exported elements, and writes a C++ source file defining the
+click_export_elements() function to the standard output.
+
+Usage: click-buildtool elem2exportstatic [-V] < elements.conf
+EOF
+	elif test "$elem2" = packagestatic; then
+	    cat <<'EOF' 1>&2
+'Click-buildtool elem2packagestatic' reads an 'elements.conf' file generated by
+'click-buildtool findelem' on the standard input, examines those files for
+exported elements, and writes a C++ source file suitable for creating a
+dynamically linked package with those elements to the standard output. PKGNAME
+is the name of the package.
+
+Usage: click-buildtool elem2packagestatic [-p PREFIX] [-V] PKGNAME < elements.conf
+EOF
 	fi
 	cat <<'EOF' 1>&2
 
@@ -981,7 +1009,7 @@ EOF
     -*)
 	elem2xxx_usage;;
     *)
-	if test -z "$package" -a "$elem2" = package; then package="$1"; shift 1; else elem2xxx_usage; fi;;
+	if test -z "$package" -a "$elem2" = package; then package="$1"; shift 1; elif test -z "$packagestatic" -a "$elem2" = packagestatic; then packagestatic="$1"; shift 1; else elem2xxx_usage; fi;;
     esac
     done
 
@@ -1031,7 +1059,119 @@ END {
   print "#ifdef CLICK_BSDMODULE\n  return 0;\n  } else\n    return 0;\n}\nstatic moduledata_t modinfo = {\n  \"", packname, "\", modevent, 0\n};\nDECLARE_MODULE(", packname, ", modinfo, SI_SUB_PSEUDO, SI_ORDER_ANY);\nMODULE_VERSION(", packname, ", 1);\nMODULE_DEPEND(", packname, ", click, 1, 1, 1);\n#else\n}\n#endif";
 }
 '
-
+    elif test -n "$packagestatic"; then
+	includes="  $includes "'print "#define WANT_MOD_USE_COUNT 1\n#include <click/config.h>\n#include <click/package.hh>\n#include <click/glue.hh>", includefiles;'
+	awk_program='BEGIN {
+  OFS = ""; nrebecca = 0; packname="'"$packagestatic"'"; includefiles=""
+}
+/^#/ { next; }
+{
+  if (NF == 1)
+    next;
+  anyprovides = 0;
+  for (i = 3; i <= NF; i++) {
+    split($i, ans, /-/);
+    if (ans[2] == "!si") {
+      B = B "  " ans[1] "::static_initialize();\n";
+      anyprovides++;
+    } else if (ans[2] == "!sc") {
+      C = C "  " ans[1] "::static_cleanup();\n";
+      anyprovides++;
+    } else if (ans[2] !~ /^!/) {
+      B = B "  hatred_of_rebecca[" nrebecca "] = click_add_element_type(\"" ans[2] "\", beetlemonkey, " nrebecca ");\n"
+      C = C "  click_remove_element_type(hatred_of_rebecca[" nrebecca "]);\n";
+      D = D "   case " nrebecca ": obj_" ans[1]".~" ans[1]"(); new (&obj_" ans[1] ") " ans[1] "; return &obj_" ans[1] ";\n";
+      E = E "extern " ans[1] " obj_"ans[1]";\n";
+      anyprovides++; nrebecca++;
+    }
+  }
+  if (anyprovides && !($2 in INCLUDES) && $2 != "-") {
+    includefiles = includefiles "\n#include " $2;
+    INCLUDES[$2] = 1;
+  }
+}
+END {
+  print "/* Generated by \"click-buildtool elem2packagestatic\" on '"$date"' */";
+  print "/* Package name: ", packname, " */\n";
+'"$includes"'
+  print E;
+  print "\nCLICK_USING_DECLS";
+  print "static int hatred_of_rebecca[", nrebecca, "];";
+  print "static Element *\nbeetlemonkey(uintptr_t heywood)\n{\n  switch (heywood) {\n", D, "   default: return 0;\n  }\n}\n";
+  print "#ifdef CLICK_LINUXMODULE\n#define click_add_element_type(n, f, t) click_add_element_type((n), (f), (t), THIS_MODULE)\n#endif";
+  print "#ifdef CLICK_BSDMODULE\nstatic int\nmodevent(module_t, int t, void *)\n{\n  if (t == MOD_LOAD) {\n#else\nextern \"C\" int\ninit_module()\n{\n#endif";
+  print "  click_provide(\"", packname, "\");\n", B, "  CLICK_DMALLOC_REG(\"nXXX\");\n  return 0;";
+  print "#ifdef CLICK_BSDMODULE\n  } else if (t == MOD_UNLOAD) {\n#else\n}\nextern \"C\" void\ncleanup_module()\n{\n#endif";
+  print C, "  click_unprovide(\"", packname, "\");";
+  print "#ifdef CLICK_BSDMODULE\n  return 0;\n  } else\n    return 0;\n}\nstatic moduledata_t modinfo = {\n  \"", packname, "\", modevent, 0\n};\nDECLARE_MODULE(", packname, ", modinfo, SI_SUB_PSEUDO, SI_ORDER_ANY);\nMODULE_VERSION(", packname, ", 1);\nMODULE_DEPEND(", packname, ", click, 1, 1, 1);\n#else\n}\n#endif";
+}
+'
+elif test "$elem2" = list; then
+	awk_program='BEGIN {
+  OFS = "";
+}
+/^#/ { next; }
+{
+  if (NF == 1)
+    next;
+  for (i = 3; i <= NF; i++) {
+    split($i, ans, /-/);
+    if (ans[2] == "!si") {
+    } else if (ans[2] == "!sc") {
+    } else if (ans[2] !~ /^!/) {
+      D = D "" ans[1] "\n";
+    }
+  }
+}
+END {
+  print D;
+}
+'
+elif test "$elem2" = exportstatic; then
+	includes="$includes"'  print "#include <click/config.h>\n#include <click/package.hh>", includefiles;'
+	awk_program='BEGIN {
+    OFS = ""; nrebecca = 0; delete objs[0];
+}
+/^#/ { next; }
+{
+  if (NF == 1)
+    next;
+  anyprovides = 0;
+  for (i = 3; i <= NF; i++) {
+    split($i, ans, /-/);
+    if (ans[2] == "!si") {
+      B = B "  " ans[1] "::static_initialize();\n";
+      anyprovides++;
+    } else if (ans[2] == "!sc") {
+      C = C "  " ans[1] "::static_cleanup();\n";
+      anyprovides++;
+    } else if (ans[2] !~ /^!/) {
+      B = B "  (void) click_add_element_type_stable(\"" ans[2] "\", beetlemonkey, " nrebecca ");\n";
+      D = D "   case " nrebecca ": obj_" ans[1]".~" ans[1]"(); new (&obj_" ans[1] ") " ans[1] "; return &obj_" ans[1] ";\n";
+      if (!(ans[1] in objs)) {
+        E = E ans[1] " obj_"ans[1]";\n";
+        objs[ans[1]] = 1;
+      }
+      anyprovides++; nrebecca++;
+    }
+  }
+  if (anyprovides && !($2 in INCLUDES) && $2 != "-") {
+    includefiles = includefiles "\n#include " $2;
+    INCLUDES[$2] = 1;
+  }
+}
+END {
+  print "/* Generated by \"click-buildtool elem2exportstatic\" on '"$date"' */\n";
+'"$includes"'
+  print E;
+  print "CLICK_USING_DECLS";
+  print "static Element *\nbeetlemonkey(uintptr_t heywood)\n{\n  switch (heywood) {\n", D, "   default: return 0;\n  }\n}\n";
+  print "#ifdef CLICK_LINUXMODULE\n#define click_add_element_type_stable(n, f, t) click_add_element_type_stable((n), (f), (t), 0)\n#endif";
+  print "void\nclick_export_elements()\n{\n", B, "  CLICK_DMALLOC_REG(\"nXXX\");\n}\n";
+  print "void\nclick_unexport_elements()\n{\n", C, "}";
+  print "void\nclick_delete_element(Element* e)\n{\n;}";
+}
+'
     else
 	includes="$includes"'  print "#include <click/config.h>\n#include <click/package.hh>", includefiles;'
 	awk_program='BEGIN {
@@ -1637,7 +1777,10 @@ on a particular tool, run 'click-buildtool TOOLNAME --help'.
 
 Usage: click-buildtool elem2make [-V] [-p PREFIX] < [ELEMENTS]
    or: click-buildtool elem2export [-V] [-p PREFIX] < [ELEMENTS]
+   or: click-buildtool elem2list [-V] < [ELEMENTS]
    or: click-buildtool elem2package [-V] [-p PREFIX] PACKAGENAME < [ELEMENTS]
+   or: click-buildtool elem2exportstatic [-V] [-p PREFIX] < [ELEMENTS]
+   or: click-buildtool elem2packagestatic [-V] [-p PREFIX] PACKAGENAME < [ELEMENTS]
    or: click-buildtool findelem [-a] [-V] [-p PREFIX] < [FILES AND DIRECTORIES]
    or: click-buildtool makepackage [-t DRIVER] PACKAGENAME SRCFILES...
    or: click-buildtool prefix
@@ -1648,7 +1791,7 @@ Usage: click-buildtool elem2make [-V] [-p PREFIX] < [ELEMENTS]
    or: click-buildtool ksyms OBJS > KSYMSFILE
    or: click-buildtool shortensyms OBJS
    or: click-buildtool compile-shortensyms [BUILD COMMAND]
-   or: click-buildtool [--cflags | --otherlibs | --toolcflags | --toollibs]
+   or: click-buildtool [--cflags | --irlibs | --otherlibs | --toolcflags | --toollibs]
 
 Options:
   -V, --verbose            Print more information.
@@ -1665,8 +1808,14 @@ EOF
      elem2="make"; shift 1; elem2make "$@"; exit 0;;
   elem2export)
      elem2="export"; shift 1; elem2xxx "$@"; exit 0;;
+  elem2list)
+     elem2="list"; shift 1; elem2xxx "$@"; exit 0;;
   elem2package)
      elem2="package"; shift 1; elem2xxx "$@"; exit 0;;
+  elem2exportstatic)
+       elem2="exportstatic"; shift 1; elem2xxx "$@"; exit 0;;
+  elem2packagestatic)
+     elem2="packagestatic"; shift 1; elem2xxx "$@"; exit 0;;
   makepackage)
      shift 1; makepackage "$@"; exit 0;;
   prefix)
@@ -1687,6 +1836,9 @@ EOF
      shift 1; compile_shortensyms "$@"; exit 0;;
   --cf|--cfl|--cfla|--cflag|--cflags|--d|--de|--def|--defs)
      echo @PROPER_INCLUDES@ @PCAP_INCLUDES@ @DPDK_INCLUDES@ @DPDK_CFLAGS@ @NETMAP_INCLUDES@ -I@includedir@; exit 0;;
+  --ir|--irl|--irli|--irlib|--irlibs)
+     echo @PROPER_LIBS@ @PCAP_LIBS@ @DL_LIBS@ @SOCKET_LIBS@ @DPDK_LIBS@ @PTHREAD_LIBS@ @POSIX_CLOCK_LIBS@ | sed -e "s/--whole-archive/--no-whole-archive/";
+     exit 0;;
   --o|--ot|--oth|--othe|--other|--otherl|--otherli|--otherlib|--otherlibs)
      echo @PROPER_LIBS@ @PCAP_LIBS@ @DL_LIBS@ @SOCKET_LIBS@ @DPDK_LIBS@ @PTHREAD_LIBS@ @POSIX_CLOCK_LIBS@;
      exit 0;;
